package matching;

/**
 * This class handles Acronym matching and parsing
 */
public class Acronym {
	
	/**
	 * @param s acronym to clean
	 * @return removes all periods from the given acronym
	 */
	public static String cleanAcronym(String s){
		String rtn = "";
		for(char c : s.toCharArray())
			if(c != '.')
				rtn += Character.toUpperCase(c);
		return rtn;
	}
	
	public static boolean acrMatch(String a1, String a2){
		char[] acr1 = a1.toCharArray();
		char[] acr2 = a2.toCharArray();
		int c1 = 0;
		int c2 = 0;
		
		while(c1 < acr1.length && c2 < acr2.length){
			if(acr1[c1] == '.')
				c1++;
			else if(acr2[c2] == '.')
				c2++;
			else if(Character.toUpperCase(acr1[c1]) != Character.toUpperCase(acr2[c2]))
				return false;
			else{
				c1++;
				c2++;
			}
		}
		return c1 >= acr1.length - 1 && c2 >= acr2.length - 1;
	}
	
	/**
	 * @param str String to compute acronym for
	 * @return null if there is only one word (not an acronym). Otherwise, 
	 * splits the string on spaces, underscores, and dashes; it returns the 
	 * acronym, which is the first character of each element generated by 
	 * the split. Result is in upper case.
	 */
	public static String computeAcronym(String str){
		String[] strParts = str.toUpperCase().split("( |_|-)");
		if(strParts.length == 1)
			return null;
		String rtn = "";
		for(String s : strParts)
			if(!s.isEmpty() && !s.matches("^(OF|THE)$"))
				rtn += s.charAt(0);
		return rtn;
	}
	
	/**
	 * @param s string to check for an acronym
	 * @return true if the given string looks like an acronym, false otherwise
	 */
	public static boolean isAcronym(String s){
		return s.matches("^([A-Z]\\.{0,1}){1,5}$");
	}
	
	/**
	 * @param acronym String that is an acronym
	 * @param str String that is not an acronym
	 * @return true if 'acronym' looks like an acronym for 'str'
	 */
	public static boolean matches(String acronym, String str){
		if(!isAcronym(acronym)) return false;
		
		if(isAcronym(str)) return false;
		
		str = str.trim().toUpperCase();
		
		String[] strParts = str.split("( |_|-)");
		String[] acrParts = parseAcronym(acronym);
		
		if(acrParts.length > strParts.length) return false;
		
		boolean rtn = true;
		int curChar = 0;
		for(int i = 0; i < strParts.length; i++){
			try{
				if(!strParts[i].matches("^(OF|THE)$")){
					rtn = rtn && (strParts[i].charAt(0) == acrParts[curChar].charAt(0));
					curChar++;
				}
			}catch(Exception e){
				return false;
			}
		}
		
		return rtn;
	}
	
	/**
	 * @param s acronym to break apart
	 * @return array with each element one character in the acronym
	 */
	public static String[] parseAcronym(String s){
		return s.matches("^([A-Z]\\.){1,}$") ? s.split("(\\.)") : s.split("");
	}
}
